config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: [:index, :show] do
    collection do
      get :linen, action: :index, type: 'Linen'
      get :clothing, action: :index, type: 'Clothing'
      get :search, as: :search
      get 'tag/:type/:tag_name(/:tag_type)', :action => :search, as: :tag
    end

  end

  get 'about' => 'home#about', as: :about
  get 'terms' => 'home#terms', as: :terms
  get 'privacy' => 'home#privacy', as: :privacy
  match 'contact_us' => 'home#contact_us', as: :contact_us, via: [:get, :post]
  get 'faq' => 'home#faq', as: :faq

  resources :blogs, only: [:index, :show] do
    collection do
      get 'page/:page', :action => :index
    end
  end

  get '/go(/:coupon_id)' => 'products#go', as: :go
  resources :questions, only: [:create]

  namespace :admin do
    resources :blogs, except: [:show]
    resources :short_urls, except: [:show]
    resources :shops, except: [:show] do
      resources :data_feeds, except: [:show] do
        member do
          get :start_sync
        end
      end
    end

    resources :products, except: [:new, :show] do
      collection do
        get '/verification(/:shop_id)' => 'products#verification', as: :verification
        get '/identification(/:shop_id)' => 'products#identification', as: :identification
      end
    end

    resources :questions, except: [:show] do
      member do
        get 'mark_as_valid'
      end
    end
  end

  get '/admin', to: redirect('/admin/products')

  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [Rails.application.secrets.admin_user, Rails.application.secrets.admin_password]
  end

  match '/*seo_url', to: 'products#short', as: :seo_url, via: :get

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id                            :integer          not null, primary key
#  name                          :string
#  shipping                      :text
#  affiliate_network_id          :string
#  affiliate_network_merchant_id :string
#  created_at                    :datetime
#  updated_at                    :datetime
#  logo                          :string
#  data_feeds_count              :integer          default("0")
#  target_url                    :string(500)
#  contact_email                 :string
#

class Shop < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  has_many :data_feeds, dependent: :delete_all
  has_many :products, dependent: :destroy
  has_many :coupons, dependent: :delete_all

  validates_presence_of :name, :shipping, :affiliate_network_id, :affiliate_network_merchant_id, :target_url
  validates_uniqueness_of :name, :affiliate_network_id
  # TOD move destroy shop do sidekiq

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < AdminController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @shops = Shop.all.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @shop = Shop.new
  end

  def edit
  end

  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to admin_shops_url, notice: 'Shop was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to admin_shops_url, notice: 'Shop was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to admin_shops_url, notice: 'Shop was successfully destroyed.' }
    end
  end

  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :logo, :opt, :target_url, :shipping, :affiliate_network_id, :affiliate_network_merchant_id)
  end
end

app/views/admin/shops/_form.html.haml
= simple_form_for [:admin, @shop] do |f|
  = f.input :name
  = f.input :logo, as: :file
  = f.input :contact_email
  = f.input :target_url
  = f.input :shipping, as: :text
  = f.input :opt
  = f.input :affiliate_network_id
  = f.input :affiliate_network_merchant_id

  .row
    .col-xs-6.col-sm-offset-6
      = f.submit 'Save', class: 'btn btn-success'

app/views/admin/shops/edit.html.haml
%h2 Редактирование магазина
= render 'form'

app/views/admin/shops/index.html.haml
%h2
  Список магазинов
  = link_to 'Новый магазин', new_admin_shop_path, class: 'btn btn-success pull-right'

%table.table.table-hover
  %tr
    %th Магазин
    %th Контактный емейл
    %th Опт
    %th Информация о доставке
    %th Партнерская сеть ID
    %th Партнер продавец ID
    %th Управление

  - @shops.decorate.each do |shop|
    %tr
      %td
        = shop.logo
        %div= shop.name
        %div= link_to("Адреса экспорта #{shop.data_feeds_count}", admin_shop_data_feeds_path(shop))
      %td= mail_to(shop.contact_email)
      %td= shop.opt
      %td= shop.shipping
      %td= shop.affiliate_network_id
      %td= shop.affiliate_network_merchant_id
      %td
        = link_to 'Модерация', verification_admin_products_path(shop_id: shop.id), class: 'btn btn-info btn-xs'
        = link_to 'Публикация', identification_admin_products_path(shop_id: shop.id), class: 'btn btn-info btn-xs'
        = link_to 'Изменить', edit_admin_shop_path(shop), class: 'btn btn-warning btn-xs'
        = link_to 'Удалить', [:admin, shop], :method => :delete, :data => { :confirm => 'Вы уверены' }, class: 'btn btn-danger btn-xs'

= paginate @shops

app/views/admin/shops/new.html.haml
%h2 New shop

= render 'form'