config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: [:index, :show] do
    collection do
      get :linen, action: :index, type: 'Linen'
      get :clothing, action: :index, type: 'Clothing'
      get :search, as: :search
      get 'tag/:type/:tag_name(/:tag_type)', :action => :search, as: :tag
    end

  end

  get 'about' => 'home#about', as: :about
  get 'terms' => 'home#terms', as: :terms
  get 'privacy' => 'home#privacy', as: :privacy
  match 'contact_us' => 'home#contact_us', as: :contact_us, via: [:get, :post]
  get 'faq' => 'home#faq', as: :faq

  resources :blogs, only: [:index, :show] do
    collection do
      get 'page/:page', :action => :index
    end
  end

  get '/go(/:coupon_id)' => 'products#go', as: :go
  resources :questions, only: [:create]

  namespace :admin do
    resources :blogs, except: [:show]
    resources :short_urls, except: [:show]
    resources :shops, except: [:show] do
      resources :data_feeds, except: [:show] do
        member do
          get :start_sync
        end
      end
    end

    resources :products, except: [:new, :show] do
      collection do
        get '/verification(/:shop_id)' => 'products#verification', as: :verification
        get '/identification(/:shop_id)' => 'products#identification', as: :identification
      end
    end

    resources :questions, except: [:show] do
      member do
        get 'mark_as_valid'
      end
    end
  end

  get '/admin', to: redirect('/admin/products')

  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [Rails.application.secrets.admin_user, Rails.application.secrets.admin_password]
  end

  match '/*seo_url', to: 'products#short', as: :seo_url, via: :get

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/short_url.rb
# == Schema Information
#
# Table name: short_urls
#
#  id          :integer          not null, primary key
#  seo_url     :string
#  full_url    :string(1024)
#  title       :string
#  description :string
#  keywords    :string
#  style_typs  :text
#  filter      :string
#  created_at  :datetime
#  updated_at  :datetime
#

class ShortUrl < ActiveRecord::Base

  validates_presence_of :seo_url, :full_url
  validates_length_of :full_url, maximum: 1024
  validates_length_of :title, maximum: 255
  validates_length_of :description, maximum: 255
  validates_length_of :keywords, maximum: 255
  validates_uniqueness_of :seo_url

  serialize :filter, Hash

  before_save :store_filter

  def store_filter
    url = self.full_url.to_s

    if url.match('/tag/')
      params = {'product' => {}}
      args = url.split('/')

      unless args[-2].eql?('tag')
        params['product'] = {args[-1] => [CGI.unescape(args[-2])]}
      else
        params['q'] = args[-1]
      end
    else
      params = Rack::Utils.parse_nested_query(url.split('?').last)
      params.delete('utf8')
    end

    unless params.blank?
      self.filter = params['product']
      self.filter['q'] = params['q'] if params['q']
    end
  end

end

app/controllers/admin/short_urls_controller.rb
class Admin::ShortUrlsController < AdminController
  before_action :set_short_url, only: [:edit, :update, :destroy]

  # GET /short_urls
  # GET /short_urls.json
  def index
    @short_urls = ShortUrl.page(params[:page]).per(10)
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # GET /short_urls/1/edit
  def edit
  end

  # POST /short_urls
  # POST /short_urls.json
  def create
    @short_url = ShortUrl.new(short_url_params)

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to admin_short_urls_path, notice: 'Short url was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /short_urls/1
  # PATCH/PUT /short_urls/1.json
  def update
    respond_to do |format|
      if @short_url.update(short_url_params)
        format.html { redirect_to admin_short_urls_path, notice: 'Short url was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /short_urls/1
  # DELETE /short_urls/1.json
  def destroy
    @short_url.destroy
    respond_to do |format|
      format.html { redirect_to admin_short_urls_path, notice: 'Short url was successfully destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_short_url
    @short_url = ShortUrl.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def short_url_params
    params.require(:short_url).permit(:seo_url, :full_url, :title, :description, :keywords, :style_typs, :filter)
  end
end

app/helpers/admin/short_urls_helper.rb
module Admin::ShortUrlsHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/admin/short_urls/_form.html.haml
= simple_form_for [:admin, @short_url] do |f|
  = f.input :seo_url, hint: 'Should url string'
  = f.input :full_url,  hint: 'Full url with products filter limit (1024)'
  = f.input :style_typs, as: :text
  %fieldset
    %legend Meta
    = f.input :title, hint: 'Page title (255 chars)'
    = f.input :description, hint: 'Page description (255 chars)'
    = f.input :keywords, hint: 'Page keywords, split by comas'
  .row
    .col-xs-3.col-sm-offset-3
    = f.submit 'Save', class: 'btn btn-success'

app/views/admin/short_urls/edit.html.haml
%h1 Editing URL

= render 'form'

app/views/admin/short_urls/index.html.haml
%h2
  Listing SEO pages
  = link_to 'New Short url', new_admin_short_url_path, class: 'btn btn-success'

%table.short_urls.table.table-hover
  %tr
    %th Meta
    %th Style typs
    %th Filter
    %th

  - @short_urls.each do |short_url|
    %tr
      %td
        = link_to(short_url.seo_url, seo_url_path(seo_url: short_url.seo_url))
        %h4 Title:
        = short_url.title
        %h4 Descriotion:
        = short_url.description
        %h5 Keywords
        = short_url.keywords
      %td= short_url.style_typs
      %td
        %pre= short_url.filter
      %td
        = link_to 'Show', seo_url_path(seo_url: short_url.seo_url)
        = link_to 'Edit', edit_admin_short_url_path(short_url)
        = link_to 'Destroy', admin_short_url_path(short_url), :method => :delete, :data => { :confirm => 'Are you sure?' }

= paginate(@short_urls)

app/views/admin/short_urls/new.html.haml
%h1 New URL

= render 'form'