config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: [:index, :show] do
    collection do
      get :linen, action: :index, type: 'Linen'
      get :clothing, action: :index, type: 'Clothing'
      get :search, as: :search
      get 'tag/:type/:tag_name(/:tag_type)', :action => :search, as: :tag
    end

  end

  get 'about' => 'home#about', as: :about
  get 'terms' => 'home#terms', as: :terms
  get 'privacy' => 'home#privacy', as: :privacy
  match 'contact_us' => 'home#contact_us', as: :contact_us, via: [:get, :post]
  get 'faq' => 'home#faq', as: :faq

  resources :blogs, only: [:index, :show] do
    collection do
      get 'page/:page', :action => :index
    end
  end

  get '/go(/:coupon_id)' => 'products#go', as: :go
  resources :questions, only: [:create]

  namespace :admin do
    resources :blogs, except: [:show]
    resources :short_urls, except: [:show]
    resources :shops, except: [:show] do
      resources :data_feeds, except: [:show] do
        member do
          get :start_sync
        end
      end
    end

    resources :products, except: [:new, :show] do
      collection do
        get '/verification(/:shop_id)' => 'products#verification', as: :verification
        get '/identification(/:shop_id)' => 'products#identification', as: :identification
      end
    end

    resources :questions, except: [:show] do
      member do
        get 'mark_as_valid'
      end
    end
  end

  get '/admin', to: redirect('/admin/products')

  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [Rails.application.secrets.admin_user, Rails.application.secrets.admin_password]
  end

  match '/*seo_url', to: 'products#short', as: :seo_url, via: :get

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  sync_hash      :string(100)      not null, primary key
#  shop_id        :integer
#  sku            :string(100)
#  slug           :string
#  name           :string
#  description    :string(2000)
#  link           :string(512)
#  brand          :string(100)
#  keywords       :string(500)
#  currency       :string(3)
#  original_image :string(512)
#  image          :string
#  original_price :integer
#  price          :integer
#  gender         :string(20)
#  state          :integer          default("0")
#  created_at     :datetime
#  updated_at     :datetime
#  is_active      :boolean          default("true")
#  cached_tags    :text
#  type           :string(15)
#

class Product < ActiveRecord::Base
  extend FriendlyId
  include AASM
  include ActionView::Helpers::SanitizeHelper
  self.primary_key = 'sync_hash'

  mount_uploader :image, ImageUploader
  acts_as_taggable_on

  belongs_to :shop
  has_many :questions, -> { where('questions.state = ?', Question.states[:verified]) }

  enum state: {draft: 0, deleted: 1, verified: 2, identified: 3, published: 4}
  serialize :cached_tags, Hash
  validates_presence_of :sku, :name, :original_image, :link, :currency, :original_price, :price
  before_save :store_tags, on: :udate

  scope :newest, -> { order('products.updated_at DESC') }
  scope :active, -> { where(is_active: true) }
  scope :opened, -> { published.active.newest }
  scope :linen, -> { where(type: 'Linen') }
  scope :clothing, -> { where(type: 'Clothing') }

  friendly_id :slug_candidates, use: :slugged

  after_commit do
    if self.published?
      self.flush_cashed_context_tags
      Rails.cache.delete('product_last_records_10')
      IndexerWorker.perform_async(:index, self.id)
    end
  end

  def slug_candidates
    [self.name, self.shop.name, self.sku].join(' ')
  end

  def to_dom_id
    "#{self.class.name.tableize}_#{self.id}"
  end

  aasm column: :state, enum: true do
    state :draft, initial: true
    state :deleted
    state :verified
    state :identified
    state :published

    #обозначили как удаленное и мы его больше не показываем нигде
    event :hide do
      transitions to: :deleted,
                  after_transition: Proc.new { |obj, *args|
                    obj.remove_all_tags
                    IndexerWorker.perform_async(:delete, obj.id) if obj.aasm.from_state.eql?(:published) }
    end

    # подтвердили продукт как нормальный для показа и отправили в очерель для создания превью
    event :verify, after: Proc.new { create_thumb } do
      transitions from: [:deleted, :draft], to: :verified
    end

    # переход когда созданы превью для продукта
    event :identify do
      transitions from: [:verified, :draft], to: :identified
    end

    # после редактирования админом продукт становится доступный в публичной части
    event :publish do
      transitions to: :published,
                  from: :identified,
                  after_transition: Proc.new { |obj, *args| obj.update_keywords }
      #IndexerWorker.perform_async(:index, obj.id)
    end
  end

  def update_keywords
    self.update_attribute(:keywords, self.cached_tags.values.flatten.join(', '))
  end

  def remove_all_tags
    self.tag_types.each { |tag_type| self.send("#{tag_type}=", []) }
  end

  def the_same_price?
    self.original_price.eql?(self.price)
  end

  def create_thumb
    ThumbWorker.perform_async(self.id)
  end

  def as_indexed_json(options={})
    self.as_json({only: [:id, :sku, :slug, :name, :description, :brand, :keywords, :price, :gender, :currency, :cached_tags, :is_active, :state],
                  include: {shop: {only: :name}},
                  methods: tag_types.collect { |type| "#{type}_list" }
                 })
  end

  def tags
    tags_hash = {}
    self.class.tag_types.each do |tags_type|
      tags = send("#{tags_type}_list".to_sym)
      tags_hash[tags_type] = tags unless tags.empty?
    end
    tags_hash
  end

  def store_tags
    self.cached_tags = tags
  end

  def related_products
    self.class.related_products(self).active.where.not(sync_hash: self.id).limit(4) rescue self.class.newest.limit(5)
  end

  def self.create_from_offer(shop_id, offer)
    product = find_or_initialize_by(sync_hash: Digest::SHA256.hexdigest("#{shop_id}-#{offer.id}")[0..35])
    if product.new_record?
      keywords = []
      keywords << offer.category.name
      keywords << offer.category.parent.name if offer.category.parent

      product.attributes = {
        shop_id: shop_id,
        sku: offer.id,
        name: offer.name || offer.model,
        description: sanitize(CGI::unescape_html(offer.description))[0..1999],
        link: offer.url,
        original_image: offer.picture,
        currency: offer.currency.id, #.name.encode('iso-8859-1').encode('utf-8'),
        price: offer.price,
        original_price: offer.price,
        brand: offer.vendor,
        keywords: keywords.join(', ')
      }
    else
      product.attributes = {
        price: offer.price,
        currency: offer.currency.id,
        is_active: offer.available
      }
    end

    unless product.save
      logger.error(product.errors.full_messages.inspect)
    end
    product
  end

  def self.create_thumb(id)
    product = find(id)
    product.remote_image_url = product.original_image
    product.save && product.identify! # : product.hide!
  end

  def self.last_records(limit = 10)
    Rails.cache.fetch("#{model_name.singular}_last_records_#{limit}", expires_in: 5.minutes) do
      self.opened.limit(limit).to_a
    end
  end

  def self.cashed_context_tags(context)
    #кешируем список контекстных тегов
    Rails.cache.fetch("#{model_name.singular}_cashed_tags_#{context}", expires_in: 5.minutes) do
      ActsAsTaggableOn::Tagging.where(context: context).joins(:tag).select('DISTINCT tags.name').map(&:name)
    end
  end

  def self.flush_cache
    Rails.cache.delete_matched(/^#{model_name.singular}/)
  end

  def cashed_context_tags(context)
    self.class.cashed_context_tags(context)
  end

  def flush_cashed_context_tags
    self.class.tag_types.each do |context|
      Rails.cache.delete("#{model_name.singular}_cashed_tags_#{context}")
    end
  end

  def tag_types
    self.class.tag_types
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.opened.includes(:shop).page(params[:page]).per(10)
  end

  def verification
    Product.friendly.find(params[:disable_ids]).map(&:hide!) if params[:disable_ids]

    @products = Product.draft.includes(:shop)
    @products = @products.where(shop_id: params[:shop_id]) if params[:shop_id]
    @products = @products.page(params[:page]).per(5)
  end

  def identification
    @product = Product.identified
    @product = @product.where(shop_id: params[:shop_id]) if params[:shop_id].present?

    if params[:id]
      @product = @product.find(params[:id])
      @product = @product.decorate
      session[:back_path] = identification_admin_products_path
      render :edit
    else
      @products = @product.page(params[:page]).per(10)
      render :index
    end
  end

  def edit
    session[:back_path] = request.referrer
  end

  def update
    if params[:state].eql?('verify')
      if @product.verified? || @product.identified?
        @product.draft!
      else
        @product.verify!
      end
    else
      params.permit!

      if @product.update(params[:product])
        @product.publish! unless @product.published?
      end
    end

    respond_to do |format|
      format.html { @product.valid? ? redirect_to(session[:back_path] || identification_admin_products_path) : render(:edit) }
      format.js {}
    end
  end

  def destroy
    @product.hide!
    respond_to do |format|
      format.html { redirect_to(request.referrer.to_s.match('identification') ? identification_admin_products_path : admin_products_path) }
      format.js {}
    end
  end

  private

  def set_product
    @product = params[:id].present? ? Product.friendly.find(params[:id]).decorate : nil
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'application'
  before_action :set_class, only: [:index, :search]

  def index
    @products = Product.opened
    @products = @products.where(type: params[:type]) if params[:type].present?
    @products = @products.page(params[:page]).per(30)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def short
    if @page = ShortUrl.where(seo_url: params[:seo_url]).first
      @products = Product.search(@page.filter.dup).page(params[:page]).records
      @selected_tags = @page.filter.except('price').values.flatten
      render :index
    else
      render file: 'home/page_404', status: 404
    end
  end

  def search
    @products = if params[:tag_name].present?
      Product.published.where(type: params[:type]).tagged_with(params[:tag_name]).page(params[:page]).per(30)
    else
      condition = ''
      if params[:q]
        condition = params[:q]
      end
      if params[:category]
        flash[:notice] = 'Category Filter not implemented yet'
        condition = '*'
      end
      if params[:product]
        condition = params[:product]
        condition[:q] = params[:q] if params[:q]
      end
      params[:type].constantize.search(condition.blank? ? '*' : condition).page(params[:page]).records
    end

    render :index
  end

  def show
    if @product = Product.friendly.includes(:shop).find(params[:id])
      @shop = Shop.find(@product.shop_id)
      @coupons = @shop.coupons.all
      @product = @product.decorate
    else
      redirect_to(root_path, notice: 'Product not found!')
    end
  end

  def go
    @redirect_url = params[:url]
    @shop = Shop.find(params[:shop_id])
    if params[:coupon_id] && (@coupon = Coupon.find(params[:coupon_id]))
      @redirect_url = @coupon.target_url unless @coupon.target_url.blank?
    end

    if @redirect_url.blank?
      redirect_to root_path, notice: 'Url not found, please contact to support!'
      return
    end
    render layout: 'simple'
  end

  private
  def set_class
    @product_class = (params[:type] || 'Product').constantize
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def selected_tag_link(type)
    selected_tags.map do |tag_name|
      link_to(tag_name, tag_products_path(type: type, tag_name: tag_name), class: 'selected_tag btn btn-default btn-xs')
    end.join(' ')
  end

  def selected_tags
    return @selected_tags if defined?(@selected_tags)
    @selected_tags = params['product'] ?
      params['product'].select { |k, v| !k.match(/price/) }.values().flatten :
      []
    @selected_tags << params[:tag_name] if params[:tag_name].present?
    @selected_tags << params[:q] if params[:q].present?
    @selected_tags
  end
end

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product] do |f|
  .row
    .col-xs-10
      = @product.image
    .col-xs-20
      .form-group
        .col-sm-6
          %label Магазин
        .col-sm-10
          = @product.shop
        .col-sm-6
          %label Бренд
        .col-sm-10= @product.brand
      = f.input :name
      = f.input :description, as: :text, input_html: {rows: 5}
      .form-group
        .col-sm-6
          %label Original price
        .col-sm-6= @product.original_price
        .col-sm-6
          %label Price
        .col-sm-6= @product.price
      .form-group
        .col-sm-6
          %label Keywords
        .col-sm-18
          = @product.keywords

  %div#tags{role: 'tabpanel'}
    %ul.nav.nav-tabs{role: 'tablist'}
      - @product.tag_types.each do |tag_type|
        %li{role: 'presentation'}= link_to(t(tag_type), "##{tag_type}",  aria:{controls:'home'}, role: 'tag',  data:{toggle:'tab'})
    .tab-content
      = render partial: 'admin/products/tags_select_list', collection: @product.tag_types, as: :tag_type, locals:{ product: @product }
  %p.text-center= f.submit 'Save', class: 'btn btn-success'

app/views/admin/products/_tags_select_list.html.haml
-#.col-xs-10.tag_type{id: tag_type}
-#  %fieldset
-#    %legend= t(tag_type) #tag_type.to_s.humanize
-#    %ul.edit-tags.list-unstyled
-#      - product.cashed_context_tags(tag_type).sort.each do |tag|
-#        %li
-#          %label
-#            = check_box_tag "product[#{tag_type}_list][]", tag, product.send("#{tag_type}_list".to_sym).include?(tag)
-#            = tag
-#    = text_field_tag :new_tag, '', data: {target: "#{tag_type}"}, placeholder: 'добавить новый тег', class: ''

.tab-pane{id: tag_type, role: 'tabpanel'}
  %ul.edit-tags.list-unstyled
    - product.cashed_context_tags(tag_type).sort.each do |tag|
      %li
        %label
          = check_box_tag "product[#{tag_type}_list][]", tag, product.send("#{tag_type}_list".to_sym).include?(tag)
          = tag
  = text_field_tag :new_tag, '', data: {target: "#{tag_type}"}, placeholder: 'добавить новый тег', class: ''

app/views/admin/products/destroy.js.haml
$('##{@product.to_dom_id}').fadeOut();

app/views/admin/products/edit.html.haml
.new-items.item-list.verification
  .row
    .col-xs-12
      - Shop.all.each do |shop|
        = link_to(shop.name, identification_admin_products_path(shop_id: shop.id), class: 'btn btn-primary')
%h1 Редактирование ##{@product.to_param}
.pull-right
  = link_to('Открыть товар', @product.link, class: 'btn btn-info', target: 'blank')
  = link_to 'Удалить', admin_product_path(@product), :method => :delete, :data => { :confirm => 'Вы уверены?'}, class: 'btn btn-warning'
= render 'form'

app/views/admin/products/index.html.haml
%h1 Товары #{action_name.eql?('identification') ? 'ожидают модерации' : 'опубликованные'}

%table.table.table-hover.item-list
  %tr
    %th Товар
    %th Ключевые слова
    %th Цена
    %th Состояние
    %th Управление

  - @products.decorate.each do |product|
    %tr.item-item{id: product.object.to_dom_id}
      %td.text-center{style: 'width: 200px'}
        = link_to(product.thumb_image, product_path(product.object))
        %div= product.name
        %label= product.shop
      %td
        = product.admin_tags_list
        %hr
        Ключевые слова: #{product.keywords}
      %td
        = product.price
      %td= product.state
      %td
        = link_to 'Изменить', edit_admin_product_path(product), class: 'btn btn-xs btn-info'
        = link_to 'Удалить', admin_product_path(product), :method => :delete, :data => { :confirm => 'Вы уверены?' }, remote: true, class: 'btn btn-xs btn-warning'

.text-center
  = paginate(@products)

app/views/admin/products/update.js.haml
- if @product.verified? || @product.identified?
  $("##{@product.to_dom_id}").addClass('verified').removeClass('pending')
- else
  $("##{@product.to_dom_id}").addClass('pending').removeClass('verified')

app/views/admin/products/verification.html.haml
.new-items.item-list.verification
  .row
    .col-xs-12
      - Shop.all.each do |shop|
        = link_to(shop.name, verification_admin_products_path(shop_id: shop.id), class: 'btn btn-primary')
  %hr/
  .row
    - @products.decorate.each do |product|
      .col-xs-15.col-sm-10.col-md-6
        .product.pending{id: product.to_dom_id, data: {id: product.id}, style: 'overflow: hidden;'}
          = link_to(image_tag(product.original_image, width: '100%', class: 'img-thumbnail'), admin_product_path(product, state: 'verify'), remote: true, method: :put)
        .clearfix
        .title
          %div= link_to(product.name, product.link, title: 'оригинал на сайте продавца', class: 'btn btn-default btn-xs', target: '_blank')
          %em
            = product.shop
        .description= strip_tags product.description
        = link_to('больше', '#', class: 'more', data: {target: "#{product.object.to_dom_id}"})
  .row.text-center
    = link_to('Пропустить все 5', '#', remote: true, class: 'btn btn-info select_all')
    - unless @products.blank?
      = link_to('Дальще', verification_admin_products_path(shop_id: @products.first.shop_id), remote: true, class: 'btn btn-success next')

app/views/admin/products/verification.js.haml
$('.new-items.item-list').replaceWith("#{j(render file: 'admin/products/verification', formats: [:html])}")