config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  resources :products, only: [:index, :show] do
    collection do
      get :linen, action: :index, type: 'Linen'
      get :clothing, action: :index, type: 'Clothing'
      get :search, as: :search
      get 'tag/:type/:tag_name(/:tag_type)', :action => :search, as: :tag
    end

  end

  get 'about' => 'home#about', as: :about
  get 'terms' => 'home#terms', as: :terms
  get 'privacy' => 'home#privacy', as: :privacy
  match 'contact_us' => 'home#contact_us', as: :contact_us, via: [:get, :post]
  get 'faq' => 'home#faq', as: :faq

  resources :blogs, only: [:index, :show] do
    collection do
      get 'page/:page', :action => :index
    end
  end

  get '/go(/:coupon_id)' => 'products#go', as: :go
  resources :questions, only: [:create]

  namespace :admin do
    resources :blogs, except: [:show]
    resources :short_urls, except: [:show]
    resources :shops, except: [:show] do
      resources :data_feeds, except: [:show] do
        member do
          get :start_sync
        end
      end
    end

    resources :products, except: [:new, :show] do
      collection do
        get '/verification(/:shop_id)' => 'products#verification', as: :verification
        get '/identification(/:shop_id)' => 'products#identification', as: :identification
      end
    end

    resources :questions, except: [:show] do
      member do
        get 'mark_as_valid'
      end
    end
  end

  get '/admin', to: redirect('/admin/products')

  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [Rails.application.secrets.admin_user, Rails.application.secrets.admin_password]
  end

  match '/*seo_url', to: 'products#short', as: :seo_url, via: :get

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route (maps HTTP verbs to controller actions automatically):
#   resources :products

# Example resource route with options:
#   resources :products do
#     member do
#       get 'short'
#       post 'toggle'
#     end
#
#     collection do
#       get 'sold'
#     end
#   end

# Example resource route with sub-resources:
#   resources :products do
#     resources :comments, :sales
#     resource :seller
#   end

# Example resource route with more complex sub-resources:
#   resources :products do
#     resources :comments
#     resources :sales do
#       get 'recent', on: :collection
#     end
#   end

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/views/layouts/_admin_header.html.haml
%nav.navbar.navbar-default.navbar-static-top{role: 'navigation' }
  .container
    = link_to('Домой', root_path, class: 'navbar-brand')

    %ul.nav.navbar-nav
      %li.dropdown
        = link_to('Продукты'.html_safe + content_tag(:span, '', class: 'caret'), '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'})
        %ul.dropdown-menu{role: 'menu'}
          %li= link_to('Опубликованные', admin_products_path)
          %li= link_to('Премодерация', verification_admin_products_path)
          %li= link_to('Публикация', identification_admin_products_path)

      %li= link_to('Магазины', admin_shops_path)
      %li= link_to('Короткие урлы', admin_short_urls_path)
      %li= link_to('Вопросы', admin_questions_path(state: 'pending'))
      %li= link_to('Блог', admin_blogs_path)

app/views/layouts/_flash.html.haml
#messagebox.alert.hide
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_footer.html.haml
%section.container
  .row
    %ul.col-xs-10.col-md-6
      %li.heading Компания
      %li= link_to('О нас', about_path)
      %li
        %a{:href => "/blogs"} Блог
      %li= link_to('Условия пользования', terms_path)
      %li= link_to('Приватность', privacy_path)
    %ul.col-xs-10.col-md-6
      %li.heading Будьте с нами
      %li
        %a{href: "https://www.facebook.com/groups/888221977903669/", rel: 'nofollow'} на Facebook
      %li
        %a{href: "https://plus.google.com/u/0/113201193942777011921/posts", rel: 'nofollow'} на Google+
    %ul.col-xs-10.col-md-6
      %li.heading Помощь
      %li
        %a{:href => faq_path} Частые вопросы
      %li
        %a{:href => contact_us_path} Обратная связь
    .col-xs-30.col-md-12
      %span.pull-right © 2014 Новенькое. Все права зарегистрированы.

app/views/layouts/_google_analytix.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60658100-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.haml
.top_line
.header
  %header
    .container.clearfix.hidden-sm.hidden-xs
      %a.logo{:href => "/"}= image_tag('logo.jpg', title: 'Мой подиум')
      -#.slogan Найдите что то новенькое

  - unless controller_name.eql?('blogs')
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#header-links"}}
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        #header-links.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to_unless_current('Одежда', '/products/clothing', title: 'Одежда') do
                %a{href: '#', class: 'active'} Одежда
            %li
              = link_to_unless_current('Белье', '/products/linen', title: 'Белье') do
                %a{href: '#', class: 'active'} Белье
          %form.form-search.navbar-form.navbar-right{action: search_products_path}
            .input-group
              %input.form-control.pull-right.search{placeholder: 'Найти...', name: 'q', value: params[:q], type: 'text'}/
              %input.type{type: 'hidden', name: 'type', value: 'Clothing'}
              .input-group-btn
                %button.btn.btn-default.dropdown-toggle{type: 'button', data:{toggle: 'dropdown'}, aria:{expanded: 'false'}}
                  Раздел
                  %span.caret
                %ul.dropdown-menu.dropdown-menu-right{role: 'menu'}
                  %li <a href="#search_clothing" data-type="Clothing">Одежда</a>
                  %li <a href="#search_linen"  data-type="Linen">Белье</a>
                  -#%li <a href="#search_accessory">Аксессуары</a>

app/views/layouts/admin.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Админ
    = stylesheet_link_tag  'application', media: 'all'
    = stylesheet_link_tag 'admin'

    = javascript_include_tag 'application'
    = javascript_include_tag 'admin'

    = csrf_meta_tags
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  %body
    = render 'layouts/admin_header'
    %section.container
      = render 'layouts/flash'
      = yield
    = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html{:lang => 'ru'}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title= yield(:page_title).blank? ? Rails.application.secrets.site_name : yield(:page_title)
    %meta{name: 'description', content: yield(:description) }
    %meta{name: 'keywords', content: yield(:keywords) }
    = yield(:meta_content)
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  %body
    = render 'layouts/header'
    .container
      - if session[:admin]
        .text-right= link_to('Управление', admin_shops_path)
      = render 'layouts/flash'
      = yield
    %footer.footer= render 'layouts/footer'
    - if Rails.env.production?
      = render 'layouts/google_analytix'

app/views/layouts/email.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Обратная связь
  %body
    %section.container
      = yield

app/views/layouts/google_analytix.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60658100-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/simple.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Новенькое
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %section.container
      = yield
    - if Rails.env.production?
      = render 'layouts/google_analytix'